################################################################################################################
#                                                                                                              #
# Specify Chat 2023® by vlouboos                                                                               #
#                                                                                                              #
# config.yml                                                                                                   #
#                                                                                                              #
################################################################################################################
DisplayMessageInConsole:
  # When set to true, every message in custom channels will be printed to console.
  # Default: false
  CustomChannels: false
  # When set to true, every message in general channel will be printed to console.
  # Default: false
  GeneralChannel: false
